title: Jason's Blog
description: Logging my life
theme: just-the-docs

url: https://jasonleex1995.github.io

search_enabled: true
favicon_ico: "/assets/chopper.ico"

aux_links:
  GitHub Repository: https://github.com/jasonleex1995
