title: Jason's Blog
description: Logging my journey of AI
theme: just-the-docs

favicon_ico: "/assets/JS.ico"
url: https://jasonleex1995.github.io

search_enabled: true

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  GitHub: https://github.com/jasonleex1995
